@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.fengmingmc.cleanenergy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;