@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.fengmingmc.cleanenergy.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;